### ISSUE TITLE
Ive got issues, man

### ISSUE THREAD

**Issue by mallyfree** [TIY-DC-ROR-2015-Sep/notes#7]
require 'HTTParty'
require 'json'
require 'pry'
# curl used to open an issue

%(curl -i -H "Authorization: token 0787ec1f04b693f555e1a34d4a78eb945bc80d22" -XPOST https://api.github.com/repos/TIY-DC-ROR-2015-Sep/notes/issues -d '{ "title": "opening issue from the terminal", "body": "here is the body" }')

key = JSON.parse(File.read "./tok.json")
git_url = "https://api.github.com/repos/TIY-DC-ROR-2015-Sep/notes/issues"
repo_issues = HTTParty.get git_url

git_headers = {
  "Authorization" => "token #{key["github"]}",
  "User-Agent"    => "this can be whatever" 
}

git_body = {
  "body" => "#{File.read("./apis.rb")}",
  "state" => "close"
}

repo_issues.each_with_index do |issue, i|
  puts i
end
patching = HTTParty.patch "https://api.github.com/repos/TIY-DC-ROR-2015-Sep/notes/issues/7", headers: git_headers, body: git_body.to_json

puts patching.message
puts patching.code

**Comment by jamesdabbs** [comment]
@mallyfree - you _did_ disable that token, right?
